# Generated by Django 4.0.4 on 2022-05-29 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('image', models.FileField(upload_to='media/%Y/%m/%d')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('view_post', models.IntegerField()),
                ('choice', models.CharField(choices=[('Travel', 'Travel'), ('LifeStyle', 'LifeStyle'), ('Healthy', 'Healthy'), ('Food', 'Food')], max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('like', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('like', models.TextField(choices=[('like', 'like'), ('dislike', 'dislike')])),
                ('comment', models.TextField()),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.news')),
            ],
        ),
    ]
