# Generated by Django 4.0.4 on 2022-05-31 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name_plural': 'Сервисы'},
        ),
    ]
